-- ANIVIA real-time messenger schema. Configure Supabase Auth before use.
create table if not exists public.social_conversations (id uuid primary key default gen_random_uuid(), kind text not null default 'direct' check (kind in ('direct','group')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.social_conversation_members (conversation_id uuid not null references public.social_conversations(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, last_read_at timestamptz, joined_at timestamptz not null default now(), primary key (conversation_id,user_id));
create table if not exists public.social_messages (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.social_conversations(id) on delete cascade, sender_id uuid not null references auth.users(id), message_text text not null check (char_length(message_text) between 1 and 1000), media_url text, created_at timestamptz not null default now(), edited_at timestamptz, deleted_at timestamptz);
create table if not exists public.social_message_reactions (message_id uuid not null references public.social_messages(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, reaction text not null, created_at timestamptz not null default now(), primary key (message_id,user_id,reaction));
create table if not exists public.social_message_notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, actor_id uuid references auth.users(id) on delete set null, conversation_id uuid references public.social_conversations(id) on delete cascade, message_id uuid references public.social_messages(id) on delete cascade, read_at timestamptz, created_at timestamptz not null default now());

alter table public.social_conversations enable row level security;
alter table public.social_conversation_members enable row level security;
alter table public.social_messages enable row level security;
alter table public.social_message_reactions enable row level security;
alter table public.social_message_notifications enable row level security;
create policy "members read conversations" on public.social_conversations for select to authenticated using (exists(select 1 from public.social_conversation_members m where m.conversation_id=id and m.user_id=auth.uid()));
create policy "members read membership" on public.social_conversation_members for select to authenticated using (user_id=auth.uid() or exists(select 1 from public.social_conversation_members own where own.conversation_id=conversation_id and own.user_id=auth.uid()));
create policy "members read messages" on public.social_messages for select to authenticated using (exists(select 1 from public.social_conversation_members m where m.conversation_id=conversation_id and m.user_id=auth.uid()));
create policy "members create messages" on public.social_messages for insert to authenticated with check (sender_id=auth.uid() and exists(select 1 from public.social_conversation_members m where m.conversation_id=conversation_id and m.user_id=auth.uid()));
create policy "users edit own messages" on public.social_messages for update to authenticated using (sender_id=auth.uid()) with check (sender_id=auth.uid());
create policy "users react in conversations" on public.social_message_reactions for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid() and exists(select 1 from public.social_messages msg join public.social_conversation_members m on m.conversation_id=msg.conversation_id where msg.id=message_id and m.user_id=auth.uid()));
create policy "own message notifications" on public.social_message_notifications for select to authenticated using (user_id=auth.uid());

create or replace function public.list_my_conversations() returns table(id uuid,name text,last_message text,last_time timestamptz,unread bigint,online boolean,last_seen text) language sql security definer set search_path=public as $$
select c.id, coalesce(p.username,'CONTACT') as name, msg.message_text, msg.created_at, 0::bigint, false, 'recently'::text from public.social_conversations c join public.social_conversation_members mine on mine.conversation_id=c.id and mine.user_id=auth.uid() join public.social_conversation_members other on other.conversation_id=c.id and other.user_id<>auth.uid() left join public.social_profiles p on p.id=other.user_id left join lateral (select message_text,created_at from public.social_messages where conversation_id=c.id and deleted_at is null order by created_at desc limit 1) msg on true order by coalesce(msg.created_at,c.updated_at) desc;
$$;
create or replace function public.list_conversation_messages(p_conversation_id uuid) returns setof public.social_messages language sql security definer set search_path=public as $$ select msg.* from public.social_messages msg join public.social_conversation_members m on m.conversation_id=msg.conversation_id where msg.conversation_id=p_conversation_id and m.user_id=auth.uid() order by msg.created_at asc; $$;
create or replace function public.send_social_message(p_conversation_id uuid,p_message_text text) returns public.social_messages language plpgsql security definer set search_path=public as $$ declare created public.social_messages; begin if not exists(select 1 from public.social_conversation_members where conversation_id=p_conversation_id and user_id=auth.uid()) then raise exception 'Not a conversation member'; end if; if exists(select 1 from public.social_blocks b join public.social_conversation_members m on m.user_id=b.blocked_id where b.blocker_id=auth.uid() and m.conversation_id=p_conversation_id) then raise exception 'Messaging blocked'; end if; insert into public.social_messages(conversation_id,sender_id,message_text) values(p_conversation_id,auth.uid(),trim(p_message_text)) returning * into created; update public.social_conversations set updated_at=now() where id=p_conversation_id; return created; end; $$;
create or replace function public.mark_conversation_read(p_conversation_id uuid) returns void language sql security definer set search_path=public as $$ update public.social_conversation_members set last_read_at=now() where conversation_id=p_conversation_id and user_id=auth.uid(); $$;

alter table public.social_messages replica identity full;
alter table public.social_message_notifications replica identity full;
alter publication supabase_realtime add table public.social_messages;
alter publication supabase_realtime add table public.social_message_notifications;
